CURRICULUM_DATA = [
    {
        "hoc_ky": "Học kỳ 1 (Năm 1)",
        "tong_tc": 19,
        "tc_hoan_thanh": 19,
        "mon_hoc": [
            {"ma_mon": "GNED1001", "ten_mon": "Triết học Mác-Lênin", "tc": 3, "loai": "Đại cương", "trang_thai": "Hoàn thành", "diem": "C+"},
            {"ma_mon": "MATH1301", "ten_mon": "Toán cao cấp A1", "tc": 4, "loai": "Đại cương", "trang_thai": "Hoàn thành", "diem": "B"},
            {"ma_mon": "PHYS1301", "ten_mon": "Vật lý đại cương", "tc": 3, "loai": "Đại cương", "trang_thai": "Hoàn thành", "diem": "C+"},
            {"ma_mon": "COMP1301", "ten_mon": "Nhập môn lập trình", "tc": 4, "loai": "Cơ sở ngành", "trang_thai": "Hoàn thành", "diem": "A"},
            {"ma_mon": "GNED1051", "ten_mon": "Tiếng Anh 1", "tc": 3, "loai": "Đại cương", "trang_thai": "Hoàn thành", "diem": "B"},
            {"ma_mon": "GNED1041", "ten_mon": "Giáo dục thể chất 1", "tc": 2, "loai": "Đại cương", "trang_thai": "Hoàn thành", "diem": "B"},
        ],
    },
    {
        "hoc_ky": "Học kỳ 2 (Năm 1)",
        "tong_tc": 18,
        "tc_hoan_thanh": 18,
        "mon_hoc": [
            {"ma_mon": "GNED1002", "ten_mon": "Kinh tế chính trị Mác-Lênin", "tc": 2, "loai": "Đại cương", "trang_thai": "Hoàn thành", "diem": "C+"},
            {"ma_mon": "MATH1302", "ten_mon": "Toán cao cấp A2", "tc": 3, "loai": "Đại cương", "trang_thai": "Hoàn thành", "diem": "B+"},
            {"ma_mon": "COMP1302", "ten_mon": "Kỹ thuật lập trình", "tc": 4, "loai": "Cơ sở ngành", "trang_thai": "Hoàn thành", "diem": "A"},
            {"ma_mon": "COMP1401", "ten_mon": "Cấu trúc dữ liệu và giải thuật", "tc": 4, "loai": "Cơ sở ngành", "trang_thai": "Hoàn thành", "diem": "B"},
            {"ma_mon": "GNED1052", "ten_mon": "Tiếng Anh 2", "tc": 3, "loai": "Đại cương", "trang_thai": "Hoàn thành", "diem": "B"},
            {"ma_mon": "GNED1042", "ten_mon": "Giáo dục thể chất 2", "tc": 2, "loai": "Đại cương", "trang_thai": "Hoàn thành", "diem": "A"},
        ],
    },
    {
        "hoc_ky": "Học kỳ 1 (Năm 2)",
        "tong_tc": 16,
        "tc_hoan_thanh": 16,
        "mon_hoc": [
            {"ma_mon": "GNED1003", "ten_mon": "Chủ nghĩa xã hội khoa học", "tc": 2, "loai": "Đại cương", "trang_thai": "Hoàn thành", "diem": "B"},
            {"ma_mon": "MATH1303", "ten_mon": "Xác suất thống kê", "tc": 3, "loai": "Đại cương", "trang_thai": "Hoàn thành", "diem": "B"},
            {"ma_mon": "COMP2201", "ten_mon": "Cơ sở dữ liệu", "tc": 4, "loai": "Cơ sở ngành", "trang_thai": "Hoàn thành", "diem": "A"},
            {"ma_mon": "COMP2301", "ten_mon": "Lập trình hướng đối tượng", "tc": 4, "loai": "Cơ sở ngành", "trang_thai": "Hoàn thành", "diem": "B+"},
            {"ma_mon": "COMP2101", "ten_mon": "Mạng máy tính", "tc": 3, "loai": "Cơ sở ngành", "trang_thai": "Hoàn thành", "diem": "C+"},
        ],
    },
    {
        "hoc_ky": "Học kỳ 2 (Năm 2)",
        "tong_tc": 18,
        "tc_hoan_thanh": 15,
        "mon_hoc": [
            {"ma_mon": "GNED1004", "ten_mon": "Lịch sử Đảng Cộng sản Việt Nam", "tc": 2, "loai": "Đại cương", "trang_thai": "Hoàn thành", "diem": "C+"},
            {"ma_mon": "COMP2401", "ten_mon": "Phân tích thiết kế hệ thống", "tc": 3, "loai": "Chuyên ngành", "trang_thai": "Hoàn thành", "diem": "B+"},
            {"ma_mon": "COMP2501", "ten_mon": "Lập trình web", "tc": 4, "loai": "Chuyên ngành", "trang_thai": "Hoàn thành", "diem": "A"},
            {"ma_mon": "COMP2601", "ten_mon": "Hệ điều hành", "tc": 3, "loai": "Cơ sở ngành", "trang_thai": "Hoàn thành", "diem": "C"},
            {"ma_mon": "COMP2701", "ten_mon": "Công nghệ phần mềm", "tc": 3, "loai": "Chuyên ngành", "trang_thai": "Hoàn thành", "diem": "B+"},
            {"ma_mon": "MATH2301", "ten_mon": "Toán rời rạc", "tc": 3, "loai": "Đại cương", "trang_thai": "Rớt", "diem": "F"},
        ],
    },
    {
        "hoc_ky": "Học kỳ 1 (Năm 3)",
        "tong_tc": 14,
        "tc_hoan_thanh": 14,
        "mon_hoc": [
            {"ma_mon": "GNED1005", "ten_mon": "Tư tưởng Hồ Chí Minh", "tc": 2, "loai": "Đại cương", "trang_thai": "Hoàn thành", "diem": "B"},
            {"ma_mon": "COMP3301", "ten_mon": "Phát triển ứng dụng di động", "tc": 3, "loai": "Chuyên ngành", "trang_thai": "Hoàn thành", "diem": "A"},
            {"ma_mon": "COMP3401", "ten_mon": "An toàn thông tin", "tc": 3, "loai": "Chuyên ngành", "trang_thai": "Hoàn thành", "diem": "B"},
            {"ma_mon": "COMP3501", "ten_mon": "Quản lý dự án phần mềm", "tc": 3, "loai": "Chuyên ngành", "trang_thai": "Hoàn thành", "diem": "B+"},
            {"ma_mon": "MATH2301", "ten_mon": "Toán rời rạc (Học lại)", "tc": 3, "loai": "Đại cương", "trang_thai": "Hoàn thành", "diem": "B"},
        ],
    },
    {
        "hoc_ky": "Học kỳ 2 (Năm 3)",
        "tong_tc": 11,
        "tc_hoan_thanh": 11,
        "mon_hoc": [
            {"ma_mon": "COMP3601", "ten_mon": "Trí tuệ nhân tạo cơ bản", "tc": 3, "loai": "Chuyên ngành", "trang_thai": "Hoàn thành", "diem": "B"},
            {"ma_mon": "COMP3701", "ten_mon": "Kiến trúc phần mềm", "tc": 3, "loai": "Chuyên ngành", "trang_thai": "Hoàn thành", "diem": "B"},
            {"ma_mon": "COMP3801", "ten_mon": "DevOps và CI/CD", "tc": 3, "loai": "Tự chọn", "trang_thai": "Hoàn thành", "diem": "B+"},
            {"ma_mon": "GNED2001", "ten_mon": "Kỹ năng giao tiếp", "tc": 2, "loai": "Đại cương", "trang_thai": "Hoàn thành", "diem": "B+"},
        ],
    },
    {
        "hoc_ky": "Học kỳ 1 (Năm 4)",
        "tong_tc": 12,
        "tc_hoan_thanh": 9,
        "mon_hoc": [
            {"ma_mon": "COMP4030", "ten_mon": "Trí tuệ nhân tạo", "tc": 3, "loai": "Chuyên ngành", "trang_thai": "Hoàn thành", "diem": "B+"},
            {"ma_mon": "COMP4028", "ten_mon": "Học máy", "tc": 3, "loai": "Tự chọn", "trang_thai": "Hoàn thành", "diem": "B"},
            {"ma_mon": "COMP3050", "ten_mon": "Kiểm thử phần mềm", "tc": 3, "loai": "Chuyên ngành", "trang_thai": "Hoàn thành", "diem": "B+"},
            {"ma_mon": "COMP4090", "ten_mon": "Đồ án chuyên ngành", "tc": 3, "loai": "Chuyên ngành", "trang_thai": "Đang học", "diem": "-"},
        ],
    },
    {
        "hoc_ky": "Học kỳ 2 (Năm 4)",
        "tong_tc": 32,
        "tc_hoan_thanh": 3,
        "mon_hoc": [
            {"ma_mon": "COMP4035", "ten_mon": "Phát triển ứng dụng", "tc": 3, "loai": "Chuyên ngành", "trang_thai": "Đang học", "diem": "-"},
            {"ma_mon": "COMP4100", "ten_mon": "Khóa luận tốt nghiệp", "tc": 10, "loai": "Chuyên ngành", "trang_thai": "Chưa học", "diem": "-"},
            {"ma_mon": "COMP4101", "ten_mon": "Xử lý ngôn ngữ tự nhiên", "tc": 3, "loai": "Tự chọn", "trang_thai": "Chưa học", "diem": "-"},
            {"ma_mon": "COMP4102", "ten_mon": "Điện toán đám mây", "tc": 3, "loai": "Tự chọn", "trang_thai": "Chưa học", "diem": "-"},
            {"ma_mon": "COMP4103", "ten_mon": "Blockchain và ứng dụng", "tc": 3, "loai": "Tự chọn", "trang_thai": "Chưa học", "diem": "-"},
            {"ma_mon": "GNED2002", "ten_mon": "Pháp luật đại cương", "tc": 2, "loai": "Đại cương", "trang_thai": "Chưa học", "diem": "-"},
            {"ma_mon": "COMP4104", "ten_mon": "Thực tập doanh nghiệp", "tc": 5, "loai": "Chuyên ngành", "trang_thai": "Chưa học", "diem": "-"},
            {"ma_mon": "GNED1053", "ten_mon": "Tiếng Anh 3", "tc": 3, "loai": "Đại cương", "trang_thai": "Chưa học", "diem": "-"},
        ],
    },
]
