STUDENT_DATA = {
    "mssv": "21110001",
    "ho_ten": "Nguyễn Văn An",
    "ngay_sinh": "15/03/2003",
    "gioi_tinh": "Nam",
    "lop": "21DTHD1",
    "khoa": "Công nghệ Thông tin",
    "nganh": "Công nghệ Phần mềm",
    "chuyen_nganh": "Kỹ thuật phần mềm",
    "khoa_hoc": "2021-2025",
    "trang_thai": "Đang học",
    "email": "21110001@sv.iuh.edu.vn",
    "sdt": "0901234567",
    "dia_chi_thuong_tru": "123 Nguyễn Văn Bá, Phường Linh Chiểu, TP. Thủ Đức, TP.HCM",
    "dia_chi_tam_tru": "45 Đường số 6, Phường Linh Trung, TP. Thủ Đức, TP.HCM",
    "gpa_tich_luy": 3.20,
    "xep_loai": "Khá",
    "tc_hoan_thanh": 85,
    "tc_tong": 140,
    "avatar_url": None,
}
