NOTIFICATIONS_DATA = [
    {
        "id": 1,
        "loai": "📢",
        "tieu_de": "Thông báo đăng ký học phần HK2 2024-2025",
        "noi_dung": "Sinh viên bắt đầu đăng ký học phần HK2 từ ngày 05/01/2025 đến 12/01/2025 trên hệ thống đào tạo.",
        "thoi_gian": "2025-01-02T08:00:00",
        "da_doc": False,
    },
    {
        "id": 2,
        "loai": "⚠️",
        "tieu_de": "Cảnh báo học vụ: Sinh viên có GPA < 2.0",
        "noi_dung": "Sinh viên có GPA tích lũy dưới 2.0 cần liên hệ cố vấn học tập trước ngày 15/01/2025.",
        "thoi_gian": "2025-01-03T10:30:00",
        "da_doc": True,
    },
    {
        "id": 3,
        "loai": "📅",
        "tieu_de": "Lịch thi cuối kỳ HK1 2024-2025",
        "noi_dung": "Lịch thi cuối kỳ HK1 đã được cập nhật. Sinh viên xem lịch thi trên hệ thống từ ngày 10/01/2025.",
        "thoi_gian": "2025-01-05T14:00:00",
        "da_doc": False,
    },
    {
        "id": 4,
        "loai": "📢",
        "tieu_de": "Hội thảo: Xu hướng AI trong phát triển phần mềm",
        "noi_dung": "Khoa CNTT tổ chức hội thảo chuyên đề về AI vào ngày 20/01/2025 tại Hội trường A. Mọi SV được mời tham dự.",
        "thoi_gian": "2025-01-08T09:00:00",
        "da_doc": False,
    },
    {
        "id": 5,
        "loai": "⚠️",
        "tieu_de": "Nhắc nhở: Đóng học phí HK2 2024-2025",
        "noi_dung": "Hạn cuối đóng học phí HK2 là ngày 25/01/2025. Sinh viên chưa đóng sẽ bị khóa tài khoản đăng ký.",
        "thoi_gian": "2025-01-10T07:00:00",
        "da_doc": False,
    },
    {
        "id": 6,
        "loai": "📅",
        "tieu_de": "Kế hoạch thực tập doanh nghiệp HK2",
        "noi_dung": "Sinh viên năm 4 đăng ký thực tập doanh nghiệp HK2 trước ngày 30/01/2025 tại Văn phòng khoa.",
        "thoi_gian": "2025-01-12T11:00:00",
        "da_doc": True,
    },
    {
        "id": 7,
        "loai": "📢",
        "tieu_de": "Cập nhật chương trình đào tạo ngành CNPM",
        "noi_dung": "Chương trình đào tạo ngành CNPM đã được cập nhật từ khóa 2024. SV các khóa trước giữ nguyên chương trình cũ.",
        "thoi_gian": "2025-01-14T16:00:00",
        "da_doc": False,
    },
]
