SCHEDULE_DATA = [
    {
        "id": "COMP4030-2-1",
        "thu": 2,
        "tiet_bat_dau": 1,
        "tiet_ket_thuc": 3,
        "mon": "Trí tuệ nhân tạo",
        "ma_mon": "COMP4030",
        "phong": "A405",
        "giang_vien": "TS. Trần Văn Hùng",
        "mau": "#4a90d9",
    },
    {
        "id": "COMP4035-2-7",
        "thu": 2,
        "tiet_bat_dau": 7,
        "tiet_ket_thuc": 9,
        "mon": "Phát triển ứng dụng",
        "ma_mon": "COMP4035",
        "phong": "B302",
        "giang_vien": "ThS. Lê Thị Mai",
        "mau": "#e67e22",
    },
    {
        "id": "COMP4028-3-1",
        "thu": 3,
        "tiet_bat_dau": 1,
        "tiet_ket_thuc": 3,
        "mon": "Học máy",
        "ma_mon": "COMP4028",
        "phong": "A301",
        "giang_vien": "PGS.TS. Nguyễn Hoàng Nam",
        "mau": "#28a745",
    },
    {
        "id": "COMP3050-3-4",
        "thu": 3,
        "tiet_bat_dau": 4,
        "tiet_ket_thuc": 5,
        "mon": "Kiểm thử phần mềm",
        "ma_mon": "COMP3050",
        "phong": "C201",
        "giang_vien": "ThS. Phạm Minh Tuấn",
        "mau": "#9b59b6",
    },
    {
        "id": "COMP4030-4-1",
        "thu": 4,
        "tiet_bat_dau": 1,
        "tiet_ket_thuc": 3,
        "mon": "Trí tuệ nhân tạo",
        "ma_mon": "COMP4030",
        "phong": "A405",
        "giang_vien": "TS. Trần Văn Hùng",
        "mau": "#4a90d9",
    },
    {
        "id": "COMP4090-4-7",
        "thu": 4,
        "tiet_bat_dau": 7,
        "tiet_ket_thuc": 9,
        "mon": "Đồ án chuyên ngành",
        "ma_mon": "COMP4090",
        "phong": "Lab3",
        "giang_vien": "TS. Võ Thành Nhân",
        "mau": "#e74c3c",
    },
    {
        "id": "COMP3050-5-4",
        "thu": 5,
        "tiet_bat_dau": 4,
        "tiet_ket_thuc": 5,
        "mon": "Kiểm thử phần mềm",
        "ma_mon": "COMP3050",
        "phong": "C201",
        "giang_vien": "ThS. Phạm Minh Tuấn",
        "mau": "#9b59b6",
    },
    {
        "id": "COMP4035-5-7",
        "thu": 5,
        "tiet_bat_dau": 7,
        "tiet_ket_thuc": 9,
        "mon": "Phát triển ứng dụng",
        "ma_mon": "COMP4035",
        "phong": "B302",
        "giang_vien": "ThS. Lê Thị Mai",
        "mau": "#e67e22",
    },
    {
        "id": "COMP4028-6-1",
        "thu": 6,
        "tiet_bat_dau": 1,
        "tiet_ket_thuc": 3,
        "mon": "Học máy",
        "ma_mon": "COMP4028",
        "phong": "A301",
        "giang_vien": "PGS.TS. Nguyễn Hoàng Nam",
        "mau": "#28a745",
    },
    {
        "id": "COMP4090-7-1",
        "thu": 7,
        "tiet_bat_dau": 1,
        "tiet_ket_thuc": 3,
        "mon": "Đồ án chuyên ngành",
        "ma_mon": "COMP4090",
        "phong": "Lab3",
        "giang_vien": "TS. Võ Thành Nhân",
        "mau": "#e74c3c",
    },
]
